"""Multi-topic fixture: 3 GitHub issues interleaved.

kubernetes/kubernetes#56903 (DNS delays)
kubernetes/kubernetes#67577 (CFS throttling)
moby/moby#13885 (Docker daemon hangs)
240 messages, chunks of 7 per topic, round-robin.
"""

CONVERSATION = [
  "@cmluciano: @kubernetes/sig-network-misc ",
  "@kgignatyev-inspur: I have similar issue: consistently slow DNS resolution from pods, 20 seconds plus\r\nfrom busybox:\r\n time nslookup google.com\r\nServer:    100.64.0.10\r\nAddress 1: 100.64.0.10\r\n\r\nName:      google.com\r\nAddress 1: 2607:f8b0:400a:806::200e\r\nAddress 2: 172.217.3.206 sea15s12-in-f14.1e100.net\r\nreal\t0m 50.03s\r\nuser\t0m 0.00s\r\nsys\t0m 0.00s\r\n/ # \r\n\r\nI just created  1.8.5 cluster in AWS with kops, and only deviation from standard config is that I am using CentOS host machines (ami-e535c59d for us-west-2)\r\n\r\nresolution from hosts is instanteneous, from pods: consistently slow\r\n",
  "@ani82: we observe the same on GKE with version v1.8.4-gke0 and both Busybox (latest) or Debian9:\r\n\r\n$ kubectl exec -ti busybox -- time nslookup storage.googleapis.com\r\nServer:    10.39.240.10\r\nAddress 1: 10.39.240.10 kube-dns.kube-system.svc.cluster.local\r\n\r\nName:      storage.googleapis.com\r\nAddress 1: 2607:f8b0:400c:c06::80 vl-in-x80.1e100.net\r\nAddress 2: 74.125.141.128 vl-in-f128.1e100.net\r\nreal\t0m 10.02s\r\nuser\t0m 0.00s\r\nsys\t0m 0.00s\r\n\r\n**DNS latency varies between 10 and 40s in multiples of 5s.**",
  "@thockin: 5s is pretty much ALWAYS indicating a DNS timeout, meaning some packet got dropped somewhere.",
  "@ani82: Yes, it seems as if the local DNS servers timeout instead of answering <not known>:\r\n\r\n[root@busybox /]# nslookup google.com\r\n;; connection timed out; trying next origin\r\n;; connection timed out; trying next origin\r\n;; connection timed out; trying next origin\r\n;; connection timed out; trying next origin\r\n;; connection timed out; trying next origin\r\n;; connection timed out; no servers could be reached\r\n\r\n\r\n[root@busybox /]# tcpdump port 53\r\ntcpdump: verbose output suppressed, use -v or -vv for full protocol decode\r\nlistening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes\r\n15:38 [trimmed]",
  "@aguerra: Just in case someone got here  because of dns delays, in our case it was arp table overflow on the nodes (arp -n showing more than 1000 entries). Increasing the limits solved the problem.",
  "@lbrictson: We have the same issue within all of our kops deployed aws clusters (5).  We tried moving from weave to flannel to rule out the CNI but the issue is the same.  Our kube-dns pods are healthy, one on every host and they have not crashed recently.  \r\n\r\nOur arp tables are no where near full (less than 100 entries usually)",
  "@neolit123: /sig node\r\n/kind bug\r\n",
  "@liggitt: is this a duplicate of #51135?",
  "@bobrik: It's similar in spirit, but it seems to miss the fact that there's an actual bug in the kernel rather than just some configuration tradeoff in CFS quota period. I've liked #51135 back here to give people there more context.",
  "@hjacobs: As far as I understand this is another reason to either disable CFS quota (`--cpu-cfs-quota=false`) or make it configurable (#63437).\r\n\r\nI also find this gist (linked from Kernel patch) very interesting to see (to gauge the impact): https://gist.github.com/bobrik/2030ff040fad360327a5fab7a09c4ff1",
  "@vishh: cc @adityakali ",
  "@juliantaylor: Another issue with quotas is that the kubelet counts hyperthreads as \"cpus\". When a cluster becomes so loaded that two threads are scheduled on the same core and the process has a cpu quota quota one of them will only perform with a small fraction of the available processing power (it will only do something when something on the other thread stalls) but still consume quota as if it had a physical core for itself. So it consumes double the quota that it should without doing significantly more work.\r\nThis has the effect that on a fully loaded node node with hyperthreading enabled the performance [trimmed]",
  "@vishh: @juliantaylor As I mentioned in #51135 turning off CPU quota might be the best approach for most k8s clusters running trusted workloads. ",
  "@duglin: would you happen to have a reduced testcase to show this? Perhaps a small Dockerfile for what's in the container and a bash script that does the work of starting/stopping/... the containers?\n",
  "@mjsalinger: Container is in dockerhub kinvey/blrunner#v0.3.8\n\nUsing the remote API with the following options:\n\nCREATE\n      Image: 'kinvey/blrunner#v0.3.8'\n      AttachStdout: false\n      AttachStderr: false\n      ExposedPorts: {'7000/tcp': {}}\n      Tty: false\n      HostConfig:\n        PublishAllPorts: true\n        CapDrop: [\n          \"CHOWN\"\n          \"DAC_OVERRIDE\"\n          \"FOWNER\"\n          \"KILL\"\n          \"SETGID\"\n          \"SETPCAP\"\n          \"NET_BIND_SERVICE\"\n          \"NET_RAW\"\n          \"SYS_CHROOT\"\n          \"MKNOD\"\n          \"SETFCAP\"\n          \"AUDIT_WRITE\"\n        ]\n        LogConfig:\n  [trimmed]",
  "@cpuguy83: Hmm, are you seeing excessive resource usage?\nThe fact that ssh isn't even working makes me suspect.\nCould very well be inode issue with overlay, or too many open FD's, etc.\n",
  "@mjsalinger: Not particularly in regards to excessive resource usage...  But the early symptom is docker completely hanging while other processes hum along happily...\n\nImportant to note, we only have 8 containers running at any one time on any one instance.\n",
  "@mjsalinger: Captured some stats where docker is no longer resposive:  \n\nlsof | wc -l \n\nshows 1025.\n\nHowever, an error appears several times:\nlsof: WARNING: can't stat() overlay file system /var/lib/docker/overlay/aba7820e8cb01e62f7ceb53b0d04bc1281295c38815185e9383ebc19c30325d0/merged\n      Output information may be incomplete.\n\n# \n\nSample output of top:\n\ntop - 00:16:53 up 12:22,  2 users,  load average: 2.01, 2.05, 2.05\nTasks: 123 total,   1 running, 121 sleeping,   0 stopped,   1 zombie\n%Cpu(s):  0.3 us,  0.0 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st\nKiB Mem:   3853940 total,  2592920 used [trimmed]",
  "@unclejack: @mjsalinger The setup you're using is unsupported. The reason why it's unsupported is that you're using Ubuntu 14.04 with a custom kernel.\n\nWhere does that 3.18.0-031800 kernel come from? Did you notice that this kernel build is outdated? The kernel you're using has been built in December last year.\n\nI'm sorry, but there's nothing to be debugged here. This issue might actually be a kernel bug related to overlay or to some other already fixed kernel bug which is no longer an issue in the latest version of kernel 3.18.\n\nI'm going to close this issue. Please try again with an up to date 3.18 or n [trimmed]",
  "@mjsalinger: @unclejack @cpuguy83 @LK4D4 Please reopen this issue.  This was advice for the configuration that we are using was specifically given by the docker team and experimentation.  We've tried newer kernels (3.19 +) and they have a kernel panic bug of some kind that we were running into - so the advice was to go with 3.18 pre-December because there was a known kernel bug introduced after that which caused a Kernel panic that we were running into, which to my knowledge, has not yet been fixed.  \n\nAs far as OverlayFS,  that was also presented to me as the ideal FS for Docker after experiencing _numero [trimmed]",
  "@bowei: There are QPS limits on DNS at various places. I think in the past, people have hit AWS DNS server QPS limits in some cases, that may be worth checking.",
  "@lbrictson: @bowei  sadly this happens in very small clusters as well for us, ones that have so few containers that there is no feasible way we'd be hitting the QPS limit from AWS",
  "@mikksoone: Same here, small clusters, no arp nor QPS limits.\r\n`dnsPolicy: Default` works without delays, but this unfortunately can not be used for all deployments.",
  "@lbrictson: @mikksoone  exact same situation as us then, dnsPolicy: Default fixes the problem entirely, but of course breaks accessing services internal to the cluster which is a no-go for most of ours.",
  "@vasartori: @bowei  We have the same problem here. \r\nBut we are not using AWS. ",
  "@vasartori: Its seems a problem with glibc.\r\nIf you set a timeout on your /etc/resolv.conf this timeout will be respected.\r\n\r\nOn CoreOS Stable (glibc 2.23) this problem appears.\r\n\r\nSetting with 0 in timeout on resolv.conf you will get a 1 secound delay....\r\n\r\nI've try disable the IPv6, without success....",
  "@vasartori: In my tests, using this option on /etc/resolv.conf \r\n`options single-request-reopen`\r\n\r\nFixed the problem.\r\nBut I don't find a \"clean\" way to put it on pods in kubernetes 1.8.\r\nWhat I do:\r\n```\r\n        lifecycle:\r\n          postStart:\r\n            exec:\r\n              command:\r\n              - /bin/sh\r\n              - -c \r\n              - \"/bin/echo 'options single-request-reopen' >> /etc/resolv.conf\"\r\n```\r\n\r\n@mikksoone Could you try if it solve your problem too?",
  "@prune998: Is this considered as a bug ? \r\n\r\nIf some pods are throttled while not really exhausting their CPU limit, it sound like a bug to me.\r\n\r\nOn my cluster, most of the over-quota pods are related to metrics (heapster, metrics-collector, node-exporter...) or Operators, which obviously have the kind of workload that is in problem here : do nothing most of the time and wake up to reconcile every once and a while.\r\n\r\nThe strange thing here is that I tried to raise the limit, going from `40m` to `100m` or `200m`, and the processes were still throttled.\r\nI can't see any other metrics pointing out a workl [trimmed]",
  "@hjacobs: @prune998 see @vishh's comment and [this gist](https://gist.github.com/bobrik/2030ff040fad360327a5fab7a09c4ff1): the Kernel over-aggressively throttles, even if the math tells you it should not. We (Zalando) decided to disable CFS quota (CPU throttling) in our clusters: https://www.slideshare.net/try_except_/optimizing-kubernetes-resource-requestslimits-for-costefficiency-and-latency-highload",
  "@prune998: Thanks @hjacobs.\r\nI'm on Google GKE and I see no easy way to disable it, but I keep searching....",
  "@timoreimann: @prune998 AFAIK, Google hasn't exposed the necessary knobs yet. We filed a feature request right after the possibility to disable CFS landed in upstream, haven't heard any news since then.",
  "@vishh: > I'm on Google GKE and I see no easy way to disable it, but I keep searching....\r\n\r\nCan you remove CPU limits from your containers for now?",
  "@mariusgrigoriu: According to the CPU manager docs, `CFS quota is not used to bound the CPU usage of these containers as their usage is bound by the scheduling domain itself.` But we're experiencing CFS throttling.\r\n\r\nThis makes the static CPU manager mostly pointless as setting a CPU limit to achieve the Guaranteed QoS class negates any benefit due to throttling.\r\n\r\nIs it a bug that CFS quotas are set at all for pods on static CPU?",
  "@hjacobs: For additional context (learned this yesterday): @hrzbrg (MyTaxi) contributed a flag to Kops to disable CPU throttling: https://github.com/kubernetes/kops/issues/5826",
  "@cpuguy83: @mjsalinger Can you provide the inode usage for the volume that overlay is running on? (`df -i /var/lib/docker` ought to do).\n",
  "@mjsalinger: Thanks for reopening.  If the answer is a different kernel, that's fine, I just want to get to a stable scenario.  \n\ndf -i /ver/lib/docker\n\nFilesystem      Inodes  IUsed  IFree IUse% Mounted on\n/dev/xvda1     1638400 643893 994507   40% /\n",
  "@unclejack: Overlay still has a bunch of problems: https://github.com/docker/docker/issues?q=is%3Aopen+is%3Aissue+label%3A%2Fsystem%2Foverlay\n\nI wouldn't use overlay in production. Others have commented on this issue tracker that they're using AUFS in production and that it's been stable for them.\n\nKernel 3.18 is unsupported on Ubuntu 14.04. Canonical doesn't provide support for that.\n",
  "@mjsalinger: AUFS in production is not performant at all and has been anything _but_ stable for us - I would routinely run into I/O Bottlenecks, freezes, etc.  \n\nSee:\n#11228, #12758, #12962\n\nSwitching to Overlay resolved all of the above issues - we only have this one issue remaining.  \n\nalso:\n\nhttp://developerblog.redhat.com/2014/09/30/overview-storage-scalability-docker/\nhttp://qconlondon.com/system/files/presentation-slides/Docker%20Clustering.pdf\n\nIt seems that Overlay is being presented as the driver of choice by the community in general.  Fine if it's not stable yet, but neither is AUFS and there has [trimmed]",
  "@mjsalinger: I also experienced symptoms similar to these running default Ubuntu instances under AUFS (12.04, 14.04, and 15.04).\n\n#10355 #13940 \n\nBoth of these issues disappeared after switching to the current Kernel and OverlayFS.\n",
  "@unclejack: @mjsalinger I'd recommend using Ubuntu 14.04 with the latest kernel 3.13 packages. I'm using that myself and I haven't run into any of those problems at all.\n",
  "@mjsalinger: @unclejack Tried that and ran into the issues specified above with heavy, high volume usage (creating/destroying lots of containers) and AUFS was incredibly non-performant.  So that's not an option.  \n",
  "@aca02djr: Also experiencing this on 1.8.6-gke.0 - @vasartori suggested solution resolved the issue for us too ",
  "@mikksoone: Doesn't solve the issue for me. Even with this option in resolv.conf I get timeouts of 5s, 2.5s and 3.5s - and they happen very often, twice per minute or so.",
  "@lauri-elevant: We have the same symptoms on 1.8, intermittent DNS resolution stall of 5 seconds. The suggested workaround seems to be effective for us as well. Thank you @vasartori !",
  "@sdtokkolabs: I've been having this issue for some time on kubernetes 1.7 and 1.8. I was dropping dns queries from time to time \r\nYesterday I upgraded my cluster from 1.8.10 to 1.9.6 (kops from 1.8 to 1.9.0-alpha.3) and I started having this same issue ALL THE TIME. The workaround sugested in this issue has no effect and I can't find any way of stopping it. I've made a small workaround by assigning the most requested (and poblematic) DNS to fixed IPs in /etc/hosts.\r\nAny idea on where the real problem is?\r\nI'll test with a brand new cluster in the same versions and report back.",
  "@xiaoxubeii: Same problem, but the most strange thing is that it appears on some nodes.",
  "@rajatjindal: @thockin @bowei \r\n\r\nrequesting your feedback therefore tagging you.\r\n\r\ncan this be of any interest here: https://tech.xing.com/a-reason-for-unexplained-connection-timeouts-on-kubernetes-docker-abd041cf7e02\r\n\r\nthere are multiple issues reported for this issue in kubernetes project, and will be great to have it resolved for everyone.",
  "@sdtokkolabs: tried with several versions of kubernetes on fresh clusters, all hae the same problem to some degree, dns lookups get lost on the way and retryes have to be made. I've also tested kubenet, flanel, canal and weave as network providers, having the lowest incidence in flanel. I've also tried overloading the nodes and splitting the nodes (dns on it's own machine) but it made no difference. On my production cluster the incidence of this issue is way higher than on a brand new cluster and i can't find the way to isolate the problem :(",
  "@alok87: Please share a summary of the problem here. It is not very clear what the problem is and in what scenarios users are impacted and what exactly is required to fix it?\r\n\r\nOur understanding at present is when we cross limits we get penaltied and throttled. So say we have a cpu quota of 3 cores and in the first 5ms we consumed 3 cores then in the 100ms slice we will get throttled for 95ms, and in this 95ms our containers cannot do anything. And we have seen to get throttled even when the cpu spikes are not visible in the cpu usage metrics. **We assume that it is because the time window of measurin [trimmed]",
  "@mariusgrigoriu: One of our users set a CPU limit and got throttled into timing out their liveness probe causing an outage of their service. \r\n\r\nWe're seeing throttling even when pinning containers to a CPU. For example a CPU Limit of 1 and pinning that container to run only on the one CPU. It should be impossible to exceed the quota given any period if your quota were exactly the number of CPU you have, yet we see throttling in every case.\r\n\r\nI thought I saw it posted somewhere that kernel 4.18 solves the problem. I haven't tested it yet, so it would be nice if someone could confirm. ",
  "@clkao: https://github.com/torvalds/linux/commit/512ac999d2755d2b7109e996a76b6fb8b888631d in 4.18 seems to be the relevant patch for this issue.",
  "@dannyk81: @mariusgrigoriu I seem to be stuck in the same conundrum you described here https://github.com/kubernetes/kubernetes/issues/67577#issuecomment-462534360.\r\n\r\nWe observe CPU throttling on Pods in Guaranteed QoS class with CPUManager static policy (which doesn't seem to make any sense).\r\n\r\nRemoving the `limits` for these Pods will put them in Burstable QoS class, which is not what we want, so the only option remaining is disable CFS cpu quotas system-wide, which is also not something we can safely do, since allowing all Pods access to unbound cpu capacity can lead to dangerous CPU saturation issu [trimmed]",
  "@mariusgrigoriu: Upgrading the kernel definitely helps, but the behavior of applying a CFS quota still seems out of alignment with what the docs suggest.",
  "@chiluk: I've been researching various aspects of this issue for a while now.  My research is summarized in my post to LKML.\r\nhttps://lkml.org/lkml/2019/3/18/706\r\nThat being said, I have not been able to reproduce the issue as described here in the pre-512ac99 kernels.  I have seen a performance regression in post-512ac99 kernels however.  So that fix is not a panacea.",
  "@dannyk81: Thanks @mariusgrigoriu, we are going for the kernel upgrade and hope that will help somewhat, also check out https://github.com/kubernetes/kubernetes/issues/70585 - it seems that quotas **are** indeed set for guaranteed pods with cpuset (i.e. pinned cpus), so this seems like a bug to me.",
  "@cpuguy83: @mjsalinger Are you using upstart to start docker? What does /etc/init/docker.conf look like?\n",
  "@mjsalinger: Yes, using upstart.\n\n/etc/init/docker.conf\n\n```\ndescription \"Docker daemon\"\n\nstart on (local-filesystems and net-device-up IFACE!=lo)\nstop on runlevel [!2345]\nlimit nofile 524288 1048576\nlimit nproc 524288 1048576\n\nrespawn\n\npre-start script\n        # see also https://github.com/tianon/cgroupfs-mount/blob/master/cgroupfs-mount\n        if grep -v '^#' /etc/fstab | grep -q cgroup \\\n                || [ ! -e /proc/cgroups ] \\\n                || [ ! -d /sys/fs/cgroup ]; then\n                exit 0\n        fi\n        if ! mountpoint -q /sys/fs/cgroup; then\n                mount -t tmpfs -o uid=0,gid [trimmed]",
  "@mjsalinger: We are also now seeing the below when running any Docker command on some instances, for example...\n\n`sudo docker ps`\n\nFATA[0000] Get http:///var/run/docker.sock/v1.18/containers/json?all=1: dial unix /var/run/docker.sock: resource temporarily unavailable. Are you trying to connect to a TLS-enabled\ndaemon without TLS?\n",
  "@LK4D4: @mjsalinger It's just crappy error message. In most cases it means that daemon crashed.\n",
  "@cpuguy83: @mjsalinger What do the docker daemon logs say during this?  `/var/log/upstart/docker.log` should be the location.\n",
  "@mjsalinger: Frozen, no new entries coming in.  Here are the last entries in the log:\n\n```\nINFO[46655] -job log(create, 48abb699bb6b8aefe042c010d06268d5e13515d616c5ca61f3a4930a325de26a, kinvey/blrunner:v0.3.8) = OK (0)\nINFO[46655] -job create() = OK (0)\nINFO[46655] POST /containers/48abb699bb6b8aefe042c010d06268d5e13515d616c5ca61f3a4930a325de26a/start\nINFO[46655] +job start(48abb699bb6b8aefe042c010d06268d5e13515d616c5ca61f3a4930a325de26a)\nINFO[46655] +job allocate_interface(48abb699bb6b8aefe042c010d06268d5e13515d616c5ca61f3a4930a325de26a)\nINFO[46655] -job allocate_interface(48abb699bb6b8aefe042c010d06268d5 [trimmed]",
  "@mjsalinger: @cpuguy83 Was the log helpful at all?\n",
  "@ghost: @sdtokkolabs Did you read the link posted by @rajatjindal in the comment previous to yours? In that one someone did isolate the problem, and also found the fix. It isn't easy to deploy, though.",
  "@sdtokkolabs: @vainu-arto , yes. The issue and fix described in that link refers to flannels use of iptables, but i don't know if it applies for the rest of the backends i've tried or docker in general :/ Is this the case?",
  "@ghost: @sdtokkolabs It applies to everything that uses NAT on Linux. I assume this is all of the backends, and also Docker using default networking.",
  "@sdtokkolabs: `cpu=0           searched=9849898 found=47461941 new=10678283 invalid=152 ignore=312 delete=12242313 delete_list=12242174 insert=10678145 insert_failed=139 drop=0 early_drop=0 error=0 search_restart=0\r\ncpu=1           searched=10363042 found=56350695 new=11674460 invalid=162 ignore=495 delete=11094956 delete_list=11094822 insert=11674330 insert_failed=130 drop=0 early_drop=0 error=2 search_restart=0\r\ncpu=2           searched=59267775 found=344890490 new=44229257 invalid=9718 ignore=5995 delete=36601710 delete_list=36601290 insert=44228850 insert_failed=348 drop=0 early_drop=0 error=55 search_r [trimmed]",
  "@rajatjindal: Can you pls share set of scrupta/commands you used to generate above stats\r\n\r\nAlso does someone has grafana dashboard template for kube-dns?",
  "@sdtokkolabs: I've run `conntrack -S` on the hosts. Same as in the url you just shared @rajatjindal.",
  "@Quentin-M: I am by the way experiencing the same thing. With Kubernetes 1.10+CoreOS+Weave+CoreDNS/kube-dns, I see constant 5s latency on DNS resolution. tcpdump shows that the first AAAA requests get lost somehow: https://hastebin.com/banulayire.swift. With `single-request` or `single-request-reopen`, the issue is gone.\r\n\r\nhttps://github.com/kubernetes/kubernetes/issues/62628",
  "@dannyk81: @chiluk could you elaborate a bit? do you mean that the patch that was included in 4.18 (mentioned above in https://github.com/kubernetes/kubernetes/issues/67577#issuecomment-466609030) doesn't actually solve the issue?",
  "@chiluk: The 512ac99 kernel patch fixes an issue for some people, but caused an issue for our configurations. The patch fixed the way time slices are distributed amongst cfs_rq, in that they now correctly expire.  Previously they would not expire.  \r\n\r\nJava workloads in particular on high core-count machines now see high amounts of throttling with low cpu usage because of the blocking worker threads. Those threads are assigned time slice which they only use a small portion of which is later expired.  In the synthetic test I wrote *(linked to on that thread), we see a performance degradation of roughly  [trimmed]",
  "@willthames: Using a 4.19.30 kernel I see pods that I'd hoped to see less throttling are still throttled and some pods that weren't previously being throttled are now being throttled quite severely (kube2iam is reporting more seconds throttled than the instance has been up, somehow)",
  "@teralype: On CoreOS 4.19.25-coreos I see Prometheus triggering CPUThrottlingHigh alert almost on every single pod in the system.",
  "@dannyk81: @williamsandrew @teralype this seems to reflect @chiluk's findings.\r\n\r\nAfter various internal discussions we in fact decided to disable cfs quotas entirely (kubelet's flag `--cpu-cfs-quota=false`), this seems to solve all the issues we've been having for both Burstable and Guaranteed (cpu pinned or standard) Pods.\r\n\r\nThere's an excellent deck about this (and few other topics) here: https://www.slideshare.net/try_except_/ensuring-kubernetes-cost-efficiency-across-many-clusters-devops-gathering-2019\r\n\r\nHighly recommended read :+1: ",
  "@dims: long-term-issue (note to self)",
  "@hjacobs: @dannyk81 just for completeness: the [linked talk](https://www.slideshare.net/try_except_/ensuring-kubernetes-cost-efficiency-across-many-clusters-devops-gathering-2019) is also available as recorded video: https://www.youtube.com/watch?v=4QyecOoPsGU",
  "@cpuguy83: @mjsalinger Makes me think there's a deadlock somewhere since there's nothing else indicating an issue.\n",
  "@mjsalinger: @cpuguy83 That would make sense given the symptoms.  Is there anything I can do to help further trace this issue and where it comes from?\n",
  "@cpuguy83: Maybe we can get an strace to see that it's actually hanging on a lock.\n",
  "@mjsalinger: Ok.  Will work to see if we can get that.  We wanted to try 1.7 first - did that but did not notice any improvement.\n",
  "@mjsalinger: @cpuguy83 From one of the affected hosts:\n\n```\nroot@<host>:~# strace -q -y -v -p 899\nfutex(0x134f1b8, FUTEX_WAIT, 0, NULL^C <detached ...>\n```\n",
  "@mjsalinger: @cpuguy83 Any ideas?\n",
  "@mjsalinger: Seeing the following in 1.7 with containers not being killed/started.  This seems to be a precurser to the problem (note didn't see these errors in 1.6 but did see a volume of dead containers start to build up, even though a command was issued to kill/remove)\n\n```\nError spawning container: Error: HTTP code is 404 which indicates error: no such container - Cannot start container 09c12c9f72d461342447e822857566923d5532280f9ce25659d1ef3e54794484: Link not found\n\nError spawning container: Error: HTTP code is 404 which indicates error: no such container - Cannot start container 5e29407bb3154d6f57786 [trimmed]",
  "@dcowden: We experience the same thing. As with Quentin-M, we see the first request most commonly fail.  ",
  "@Quentin-M: I would just like to add here that the `single-request(-reopen)` workaround does not work with Alpine-based containers, as musl does not support the option (see below). Unfortunately, Alpine Linux is the base image of 90% of our infrastructure.\r\n\r\n[src/network/resolvconf.c](https://git.musl-libc.org/cgit/musl/tree/src/network/resolvconf.c)\r\n```\r\n                if (!strncmp(line, \"options\", 7) && isspace(line[7])) {\r\n                        p = strstr(line, \"ndots:\");\r\n                        if (p && isdigit(p[6])) {\r\n                                p += 6;\r\n                                un [trimmed]",
  "@Quentin-M: @adnankobir Could you describe how does bind-tools help exactly? The package [only include](https://pkgs.alpinelinux.org/contents?branch=edge&name=bind-tools&arch=x86&repo=main) binaries such as dig, nslookup, while the issue is present at the kernel level, triggered by libc's behavior on lookups, itself triggered by applications' code directly. Were those binaries triggering the bug themselves, and now does not anymore? \r\n\r\nI have however developed last week a [workaround](https://github.com/weaveworks/weave/issues/3287#issuecomment-390383565) based on the use of [tc](http://man7.org/linux/ma [trimmed]",
  "@KIVagant: FYI: `single-request-reopen` didn't help in my case (https://github.com/kubernetes/kubernetes/issues/56903#issuecomment-359897058)\r\n\r\nKubernetes 1.10, AWS\r\n\r\n```\r\n# cat /etc/resolv.conf\r\nnameserver 100.64.0.10\r\nsearch default.svc.cluster.local svc.cluster.local cluster.local ec2.internal\r\noptions ndots:5\r\noptions single-request-reopen\r\n```\r\n\r\n```\r\nCaused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/100.64.0.10:53] query timed out after 5000 milliseconds (no stack trace available)\r\n```\r\nOS in container:\r\n```\r\nPRETTY_NAME=\"Debian GNU/Linux 9 (stretch)\"\r\nNAME=\"Debian GNU/Linux\"\r\nV [trimmed]",
  "@Quentin-M: @KIVagant \r\n\r\nThis is a libc option, this does not generally depend on the application but on the libc used. Except if they have their own implementation of the resolv stack (which I don't know for OpenJDK/Netty)\r\n\r\nPlease however confirm that the issue actually comes from the conntrack race condition we are talking about, or something else. To confirm, use `watch -n1 conntrack -S` and check whether the `insert_failed` column is increasing as you are getting time-outs.\r\n\r\nMy tc-based workaround should fix your issue if that's the case.",
  "@KIVagant: @Quentin-M , I've been waiting for a while and now can say that `insert_failed` column is not increasing when I'm getting new DNS errors in the application log.\r\n\r\n```\r\n$ kubectl logs my-service-5466c54fdf-g2vfb | grep \"failed to resolve\" | wc -l\r\n22\r\n$ kubectl exec -it my-service-5466c54fdf-g2vfb -- conntrack -S\r\nentries   \t\t90\r\nsearched  \t\t2228\r\nfound     \t\t3774748\r\nnew       \t\t132421\r\ninvalid   \t\t1\r\nignore    \t\t0\r\ndelete    \t\t327481\r\ndelete_list\t\t327481\r\ninsert    \t\t132421\r\ninsert_failed\t\t0\r\ndrop      \t\t0\r\nearly_drop\t\t0\r\nicmp_error\t\t0\r\nexpect_new\t\t0\r\nexpect_create\t\t0\r\nexpect_delete\t\t0\r\nsear [trimmed]",
  "@Quentin-M: @KIVagant What about on the hosts themselves (conntrack -S)?",
  "@agolomoodysaada: @hjacobs , loved the talk! Thanks a lot...\r\nAny idea how to apply this fix on AKS or GKE?\r\nThanks",
  "@timoreimann: @agolomoodysaada we filed a feature request with GKE a while back. Not sure what the status is though, I do not work intensively with GKE anymore.",
  "@agolomoodysaada: I reached out to Azure support and they said it won't be available until around August 2019.",
  "@agolomoodysaada: <img width=\"1423\" alt=\"Screen Shot 2019-04-04 at 3 54 00 PM\" src=\"https://user-images.githubusercontent.com/29459870/55629839-3353b680-5782-11e9-8dff-d57a2ae937cb.png\">\r\nThought I would share a graph of an application consistently throttled throughout its lifetime.",
  "@chiluk: What kernel was this on?",
  "@agolomoodysaada: @chiluk \"4.15.0-1037-azure\"",
  "@chiluk: So that doesn't contain kernel commit 512ac99.  Here's the corresponding\nsource.\nhttps://kernel.ubuntu.com/git/kernel-ppa/mirror/ubuntu-azure-xenial.git/tree/kernel/sched/fair.c?h=Ubuntu-azure-4.15.0-1037.39_16.04.1&id=19b0066cc4829f45321a52a802b640bab14d0f67\n\nWhich means you might be hitting the issue described in 512ac99.  Keep in\nmind that 512ac99 brought other regressions for us.\n\nOn Fri, Apr 5, 2019 at 12:08 PM Moody Saada <notifications@github.com>\nwrote:\n\n> @chiluk <https://github.com/chiluk> \"4.15.0-1037-azure\"\n>\n> \n> You are receiving this because you were mentioned.\n> Reply to this e [trimmed]",
  "@mjsalinger: Tail of docker.log from a recent incident:\n\n```\nINFO[44089] DELETE /containers/4e455d01da8453688dd27cad41fea158757311c0c89f27619a728f272591ef25?force=true\nINFO[44089] +job rm(4e455d01da8453688dd27cad41fea158757311c0c89f27619a728f272591ef25)\nINFO[44089] DELETE /containers/a608bc1014317b083ac2f32a4c6c85dda65445420775e21d6406ca9146723c96?force=true\nINFO[44089] +job rm(a608bc1014317b083ac2f32a4c6c85dda65445420775e21d6406ca9146723c96)\nINFO[44089] +job log(die, 4e455d01da8453688dd27cad41fea158757311c0c89f27619a728f272591ef25, kinvey/blrunner:v0.3.8)\nINFO[44089] -job log(die, 4e455d01da8453688dd27cad [trimmed]",
  "@mjsalinger: @cpuguy83 @LK4D4 Any ideas/updates?\n",
  "@LK4D4: Have no idea, what to think. It isn't software deadlock, because even docker info hanging. Can this be memory leak?\n",
  "@mjsalinger:  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND\nroot      20   0 1314832  89688  11568 S   0.3  2.3  65:47.56 docker\n\nThat's what the Docker process looks to be using; doesn't look too much like a memory leak to me...\n",
  "@nicolasnoble: I'll comment on that one to say \"us too\". We're using Docker for our testing infrastructure, and we're hit by that within the same conditions / scenarios. This is going to impact our ability to use Docker in a meaningful manner if it locks up under load.\n\nI'd be happy to contribute troubleshooting results if you would point me at what you'd need as information.\n",
  "@filex: I just ran into the same issue on a CentOS7 host.\n\n```\n$ docker version\nClient version: 1.6.2\nClient API version: 1.18\nGo version (client): go1.4.2\nGit commit (client): ba1f6c3/1.6.2\nOS/Arch (client): linux/amd64\nServer version: 1.6.2\nServer API version: 1.18\nGo version (server): go1.4.2\nGit commit (server): ba1f6c3/1.6.2\nOS/Arch (server): linux/amd64\n```\n\n```\n$ docker info\nContainers: 7\nImages: 672\nStorage Driver: devicemapper\n Pool Name: docker-253:2-67171716-pool\n Pool Blocksize: 65.54 kB\n Backing Filesystem: xfs\n Data file: /dev/mapper/vg01-docker--data\n Metadata file: /dev/mapper/vg01-doc [trimmed]",
  "@fishnix: We are seeing the same thing as @filex on Centos 7 in our CI environment\n\n```\nContainers: 1\nImages: 19\nStorage Driver: devicemapper\n Pool Name: docker--vg-docker--pool\n Pool Blocksize: 524.3 kB\n Backing Filesystem: xfs\n Data file:\n Metadata file:\n Data Space Used: 2.611 GB\n Data Space Total: 32.17 GB\n Data Space Available: 29.56 GB\n Metadata Space Used: 507.9 kB\n Metadata Space Total: 54.53 MB\n Metadata Space Available: 54.02 MB\n Udev Sync Supported: true\n Deferred Removal Enabled: true\n Library Version: 1.02.93-RHEL7 (2015-01-28)\nExecution Driver: native-0.2\nLogging Driver: json-file\nKernel V [trimmed]",
  "@KIVagant: ```\r\nkubectl get node |grep -v NAME |  awk '{print $1}' | xargs -i sh -c 'ssh admin@{} -- hostname -f; sudo conntrack -S'\r\n\r\nip-10-111-115-29.ec2.internal\r\ncpu=0   \tsearched=209446 found=39800914 new=1831916 invalid=2889 ignore=7053695 delete=1831782 delete_list=1831782 insert=1831916 insert_failed=0 drop=0 early_drop=0 error=102 search_restart=0\r\ncpu=1   \tsearched=0 found=0 new=0 invalid=0 ignore=0 delete=0 delete_list=0 insert=0 insert_failed=0 drop=0 early_drop=0 error=0 search_restart=0\r\ncpu=2   \tsearched=0 found=0 new=0 invalid=0 ignore=0 delete=0 delete_list=0 insert=0 insert_failed=0 dr [trimmed]",
  "@Quentin-M: So unfortunately it does seem that the issue you are having is different\nthan the one experienced by various folks here, and that is related to a\nconntrack race,\n",
  "@codebreach: We are also facing this GKE and is making the everything unusable.\r\nThe CloudSQL proxy sidecar fails with i/o timeouts on DNS. Making all app serving pods enter a crash loop.\r\n\r\nI have verified that I can access using ClusterIP but not using DNS.\r\n\r\nIs there a workaround for GKE-Container OS users?",
  "@bboreham: Just joining some dots:\r\nhttps://github.com/weaveworks/weave/issues/3287\r\nhttps://github.com/kubernetes/kubernetes/issues/45976\r\n\r\nand while I'm talking about dots let me recommend using fully-qualified names where possible, e.g. `google.com.` - the dot at the end stops the resolver from following the search path, so you don't get lookups for `google.com.svc.cluster.local.` and so on.",
  "@Quentin-M: I just posted a little write-up about our journey troubleshooting the issue, and how we are worked around it in production: https://blog.quentin-machu.fr/2018/06/24/5-15s-dns-lookups-on-kubernetes/.",
  "@maxlaverse: Thanks for sharing this @Quentin-M.\r\n\r\n> This means that adding --random-fully does fix the packet loss, as the flag only acts on the SNAT race!\r\n\r\nI believe there is a typo here and you meant **does not** fix the packet loss.\r\n\r\nI'll use this opportunity to clarify one point ;)\r\n\r\nI hope the article about [connection timeouts on Kubernetes](https://tech.xing.com/a-reason-for-unexplained-connection-timeouts-on-kubernetes-docker-abd041cf7e02) was not misleading but this flag `NF_NAT_RANGE_PROTO_RANDOM_FULLY` (or its user-space switch equivalent `--random-fully`) **is not supposed to fix anythin [trimmed]",
  "@Quentin-M: @maxlaverse Thank you for your note about the typo, for the word usage of \"fix\" that I replaced with \"mitigate\", and for your great initial troubleshooting work!\r\n\r\n> You've tested the ipvs back-end of kube-proxy and it didn't solve the issue.\r\n\r\nThis is what we use daily, yes.\r\n\r\n> The lvs wiki states that the ipvs module uses its own connection tracking system. Since there is only network adress translation to be done, and no filtering or other kind of mangling involved, I had good hope it would work better. Do you know why ?\r\n\r\nThis is is great find, I was not aware at all. Given the wordin [trimmed]",
  "@chiluk: I have now posted patches to LKML about this.\r\nhttps://lkml.org/lkml/2019/4/10/1068\r\n\r\nAdditional testing would be greatly appreciated.",
  "@chiluk: I resubmitted these patches now with documentation changes.\r\nhttps://lkml.org/lkml/2019/5/17/581\r\n\r\nIt would really help if people could test these patches and comment on the thread on LKML.  At the moment I'm the only one to have mentioned this at all on LKML, and I have not received any comments whatsoever from the community or the maintainers.  It would really go a long way if I could get some community testing and commentary on LKML under my patch.",
  "@agolomoodysaada: For what it's worth, this particular project https://github.com/tensorflow/serving seems to be severely impacted by this issue. And it's mostly a C++ application. \r\n\r\n@chiluk , Are there any workarounds we can apply while the patch gets rolled out?\r\nThank you very much",
  "@whereisaaron: We should help @chiluk collect citations of serious impact of this kernel bug on Kubernetes and anyone else using CFS quotas.\r\n\r\nZolando included in their presentation last week that their bad experiences with the current kernel means that they consider disabling CFS quotas as current Best Practice, as they consider it does more harm than good.\r\nhttps://www.youtube.com/watch?v=6sDTB4eV4F8",
  "@hjacobs: More and more companies are disabling CPU throttling, e.g. mytaxi, Datadog, Zalando ([Twitter thread](https://twitter.com/try_except_/status/1131459031376252928))",
  "@dims: @derekwaynecarr @dchen1107 @kubernetes/sig-node-feature-requests Dawn, Derek, is it time to change the default? and/or documentation?",
  "@chiluk: Yes @whereisaaron collecting and sharing reports of throttling crippling applications, and or being turned off because of it's bad behavior would be welcome participation on the lkml thread where appropriate.  At the moment it looks like it's mostly just me complaining about this issue to the kernel community.",
  "@avanja: Same here: docker was not responding to ps, rm, stop, run, info and probably more. A few reboots later, everything was back to normal. \n\n<pre>\ndocker info\nContainers: 25\nImages: 1739\nStorage Driver: devicemapper\n Pool Name: docker-9:2-62521632-pool\n Pool Blocksize: 65.54 kB\n Backing Filesystem: extfs\n Data file: /dev/loop0\n Metadata file: /dev/loop1\n Data Space Used: 96.01 GB\n Data Space Total: 107.4 GB\n Data Space Available: 11.36 GB\n Metadata Space Used: 110.5 MB\n Metadata Space Total: 2.147 GB\n Metadata Space Available: 2.037 GB\n Udev Sync Supported: true\n Deferred Removal Enabled: false\n D [trimmed]",
  "@whosthatknocking: I'm on 1.6.2 and 1.8.2 and my docker setup is also melting under load. It looks like docker job queue is slowly filling up to the point where any new calls take minutes. Tuning filesystem and keeping small number of containers makes things a bit better. I'm still looking into this searching for some patterns.\n\n```\n$ docker version\nClient:\n Version:      1.8.2\n API version:  1.20\n Go version:   go1.4.2\n Git commit:   44b3b67\n Built:        Mon Sep 14 23:56:40 UTC 2015\n OS/Arch:      linux/amd64\n\nServer:\n Version:      1.8.2\n API version:  1.20\n Go version:   go1.4.2\n Git commit:   44b3b67\n Buil [trimmed]",
  "@ohade: Same here. I sure am happy to have found this thread, i was loosing my mind for the past two weeks trying to see what the problem might be.\nI think its the amount of containers that are being started simultaneously, it look like a classic case of a deadlock.\n",
  "@filex: in my case, it was only a hand full of containers being started simultaneously (maybe 3-5). but all of them receive a large input stream through STDIN (of docker run), which may have put extra stress on the daemon.\n",
  "@thom4parisot: @filex have a similar use case. Although we did not face these freeze before we migrated to 1.8.2\n",
  "@PlugIN73: Today i meet problems like this - docker ps frozen, docker eat 100% cpu. \nAnd now i see that my datadog-agent asked docker in loop about it's containers with this option:\n\n```\ncollect_container_size: true\n```\n\nSo i have infinity loop with very hard operation (i have more than 10k containers). After i stopped datadog docker integration, system runnig ok - docker ps worked, docker eat 0% cpu.\n",
  "@whosthatknocking: I'm experimenting with cadvisor and it's also melting docker.. Try to reduce number of dead, exited containers and see if that reduces the load.\n",
  "@mikksoone: Thanks for all the nice writeups regarding S(D)NAT races.\r\n\r\nI (OP) did some testing, and in my case, it's not the race, but something else is throttling DNS. Switching from alpine to ubuntu + options single-request-reopen, made the slow requests even slower. So I decided to see if there are periods when DNS is slow - and indeed, using 8 pods to see when they encounter the slow DNS, this is the chart that came out:\r\n![chart 1](https://user-images.githubusercontent.com/1069008/41973041-80af8a38-7a1c-11e8-9985-1499965e4521.png)\r\n\r\n\r\nBasically if DNS is slow, then it's slow for many pods at the s [trimmed]",
  "@dcowden: wow @mikksoone that is awesome work!  That's definitely an unquestionably regular pattern!  ",
  "@maxlaverse: > this is the chart that came out\r\n\r\nThe Y axis is the number of slow lookups ? After how much time is a lookup considered to be slow ?\r\n\r\n> kube-dns is not being CPU throttled\r\n\r\nJust to rule throttling out, you know this because you haven't set any CPU limit or you could see that `/sys/fs/cgroup/cpu/kubepods/.../nr_throttled = 0` (or equivalent) ?\r\n\r\n> My plan is now to understand if the problem is between pod and kube-dns or between kube-dns and external dns\r\n\r\nWe run tiny Go program as DaemonSet querying CoreDNS (10.96.0.10) (previously kube-dns) and the upstream DNS every few seconds, to  [trimmed]",
  "@mikksoone: > The Y axis is the number of slow lookups ? After how much time is a lookup considered to be slow ?\r\n\r\nSorry for the missing axes, updated the chart. Y is duration in seconds, x is the datetime of request in seconds since epoch. It's considered slow if the request takes more than a second.\r\n\r\n> Just to rule throttling out, you know this because you haven't set any CPU limit or you could see that /sys/fs/cgroup/cpu/kubepods/.../nr_throttled = 0 (or equivalent) ?\r\n\r\nHaven't checked nr_thottled = 0, will do now, but because I see there is no limit, the request is set to 100 + 150 + 10 and promet [trimmed]",
  "@maxlaverse: > Haven't checked nr_thottled = 0, will do now, but because I see there is no limit, the request is set to 100 + 150 + 10 and prometheus is reporting < 30+30+2 for peaks. (kube-dns+dnsmasq+sidecar)\r\n\r\nNo need to check `nr_thottled` then. If no limit is set it should be 0, or the key is probably not even there\r\n\r\n> It's 1.9 so yes, I can try with \"None\", but I don't have a good idea what configurations to test. With \"default\" it works well, no timeouts ever.\r\n\r\nThe value \"default\" is also fine, that's why I wanted to know, by-passing the in-cluster DNS\r\n\r\n> It's not that weird if you consider t [trimmed]",
  "@KIVagant: > @KIVagant have you tested if the problem is also appearing periodically for everyone?\r\n\r\n@mikksoone, no, I haven't. We decided to move the most problematic service out of K8s because we also found couple of critical issues not related to this one. After this I didn't research this problem with DNS.",
  "@dermyrddin: https://github.com/kubernetes/kubernetes/issues/56903#issuecomment-359897058 doesn't work for me too.\r\n\r\nHost: Debian GNU/Linux 9 (stretch)   4.9.0-6-amd64\r\nImage: Ubuntu 16.04\r\nkube 1.9.3 via kops 1.9.1 on aws",
  "@chiluk: @agolomoodysaada the workaround is to temporarily disable cfs quotas or over-allocate cpu quota to affected applications *(not all applications will hit this, but the majority of multi-threaded user-interactive applications probably are).\r\n\r\nThere's also best practices around reducing application thread count which also helps.\r\nFor golang set GOMAXPROCS~=ceil(quota)\r\nFor java move to the newer JVMs that recognize and respect cpu quota limits.  Earlier jvms spawned threads based on the number of CPU cores, not the number of cores available to the application.\r\nBoth of these have been major boon [trimmed]",
  "@prune998: FYI, after I pointed out this thread to the Azure AKS support, I was answered the patch will be rolled out when they upgrade to kernel 5.0, in late september, at best.\r\nUntil then, well, stop using limits :)",
  "@dannyk81: @prune998 there's a small caveat there in case you are using CPUmanager (i.e. dedicated cpu allocation to pods in Guaranteed QoS).\r\n\r\nBy removing limits you will avoid the CFS throttling issue, but you will remove the pods from Guaranteed QoS so CPUmanager will not allocate dedicated cores for these pods anymore.\r\n\r\nIf you don't use CPUmanager - no harm done, but just FYI for anyone opting for this direction.\r\n\r\nThere is a PR (https://github.com/kubernetes/kubernetes/issues/70585) to disable CFS quotas entirely for Pods with dedicated CPUs however it was not merged yet.\r\n\r\nWe have also opted t [trimmed]",
  "@dims: @dannyk81 https://github.com/kubernetes/kubernetes/issues/70585 is not a PR that can be merged (it's an issue with a code snippet). Can you (or someone else) please file a PR?",
  "@praseodym: Theres one already: https://github.com/kubernetes/kubernetes/pull/75682",
  "@dannyk81: @dims I linked the issue, not the PR... but the issue is linked to the PR :) indeed it is https://github.com/kubernetes/kubernetes/pull/75682 and it's been hanging there for a while, so if you could push this would be great as this is really an annoying issue.\r\n\r\nThanks :+1: ",
  "@dims: whoops! thanks @dannyk81 i've assigned folks and added milestone",
  "@ohade: Can you please elaborate more on your findings?\n\nOn Thu, Oct 1, 2015, 00:23 Alexander Vagin notifications@github.com wrote:\n\n> Today i meet problems like this - docker ps frozen, docker eat 100% cpu.\n> And now i see that my datadog-agent asked docker in loop about it's\n> containers with this option:\n> \n> collect_container_size: true\n> \n> So i have infinity loop with very hard operation (i have more than 10k\n> containers). After i stopped datadog docker integration, system runnig ok -\n> docker ps worked, docker eat 0% cpu.\n> \n> \n> Reply to this email directly or view it on GitHub\n> https://gith [trimmed]",
  "@PlugIN73: @ohade my docker works without any freezes 24/7. On every time it has 60-80 started containers. I have about 1500 new containers in one day. So when i saw that with this load it has freezes and only from docker (system have many free memory, io, cpu), i thinked that it's not a common problem. \nI found someone sends requests to my docker in logs (/var/log/upstart/docker.logs). And i found who it was :) \nWhat tell you more?\n",
  "@ohade: :) I ment, is that agent a part of the docker and I can turn it size\nchecking too, or is it external agent?\n\nOn Thu, Oct 1, 2015, 14:03 Alexander Vagin notifications@github.com wrote:\n\n> @ohade https://github.com/ohade my docker works without any freezes\n> 24/7. On every time it has 60-80 started containers. I have about 1500 new\n> containers in one day. So when i saw that with this load it has freezes and\n> only from docker (system have many free memory, io, cpu), i thinked that\n> it's not a common problem.\n> I found someone sends requests to my docker in logs\n> (/var/log/upstart/docker.logs) [trimmed]",
  "@PlugIN73: @ohade no, it isn't a part of the docker. My opinion that it isn't docker issue. You must look your environment for heavy requests to docker.\n",
  "@naglalakk: I'm having this issue as well since I updated to docker 1.8.2\n",
  "@jtattermusch: Any progress on this? In our testing infrastructure, I am spinning up a large number or short lived containers and I am running into this issue more than once a day. \n",
  "@jtattermusch: ```\ndocker version\nClient:\n Version:      1.8.2\n API version:  1.20\n Go version:   go1.4.2\n Git commit:   0a8c2e3\n Built:        Thu Sep 10 19:12:52 UTC 2015\n OS/Arch:      linux/amd64\nServer:\n Version:      1.8.2\n API version:  1.20\n Go version:   go1.4.2\n Git commit:   0a8c2e3\n Built:        Thu Sep 10 19:12:52 UTC 2015\n OS/Arch:      linux/amd64\n```\n\nLinux version:\n\n```\n$ uname -a\nLinux grpc-interop1 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3~bpo70+1 (2015-08-08) x86_64 GNU/Linux\n```\n",
  "@jsenon: Hi, in your alpine pod have you tried to add: `apk -v --update add  --no-cache bind-tools` ?",
  "@inter169: [ld-musl-x86_64.so.1-fix-musl-1.1.18-r3-alpine3.7.tar.gz](https://github.com/kubernetes/kubernetes/files/2250076/ld-musl-x86_64.so.1-fix-musl-1.1.18-r3-alpine3.7.tar.gz)\r\n\r\nThis bug described a few different types of slow DNS queries, \r\nin my use case the slow DNS requests occurred on alpine:3.7/3.8, due to the timed out for additional AAAA query along with A query by default.\r\ncurrently no need to query AAAA records by default, so the solution is removing AAAA resolution from the implements (musl/src/network/lookup_name.c, function 'name_from_dns'), and the code fix worked for me:\r\n```\r\n    / [trimmed]",
  "@Quentin-M: See https://blog.quentin-machu.fr/2018/06/24/5-15s-dns-lookups-on-kubernetes/ for a more in-depth description of the issue on Kubernetes and a workaround that doesnt involve rewriting musl or glibc.",
  "@inter169: yes, but I don't want to involve additional tc shell codes & iptables rules into my kubernetes production nodes, neither a little bit more latency for processing AAAA queries by default.\r\n\r\nthe fix worked for cases which no need for AAAA (ipv6) by default on alpine linux.",
  "@szuecs: @Quentin-M I ported your proposed solution to flannel and I don't see much better behaviour. Relying on a less likely happening of a race condition by delaying packets is IMHO also a weak way of \"synchronization\". Maybe it is the right solution if you don't need IPv6. I guess sooner or later I will test it, thanks @inter169 ",
  "@Quentin-M: Improvement was complete for us, and several others. The port in the parsing logic simply needs to be adapted depending on what port your DNS server exposes.\n\nThe rationale is that patching glibc/musl in ten thousand containers is arguably harder than dropping a script that workaround the root cause by adding 3ms to IPv6 DNS lookups - especially when you consider that the kernel is eventually going to fix it.\n\nAdditionally, separation of concerns is important to us, this is an infrastructure related issue, cluster users should not have to even know about it.\n\n> On Aug 3, 2018, at 02:34, Sandor [trimmed]",
  "@dcowden: @Quentin-M we're trying to determine if your fix will work for us.  We're  using the test tool here https://github.com/thomaschaaf/dns-tester to easily reproduce this issue in our cluster.  However, on the node the test pod is running on, insert_failed is not growing with the failures.\r\n\r\nDoes this mean your fix wont work? or does the insert_failed count grow on the host for the target container, not the one with the source pod on it?\r\n",
  "@d-shi: FWIW we ran into this issue as well, and found that dropping the CFS quota period to 10ms instead of the default 100ms caused our tail end latencies to improve dramatically. I think this is because even if you run into the kernel bug, a far shorter amount of quota is wasted if it is not used, and the process can get more quota (in smaller allotments) much sooner. This is just a workaround, but for those who don't want to disable CFS quota entirely, this could be a bandaid until the fix is implemented. k8s supports doing this in 1.12 with the cpuCFSQuotaPeriod feature gate and --cpu-cfs-quota-p [trimmed]",
  "@chiluk: I'd have to check, but I think shrinking the period down that far may have the effect of effectively disabling it, as there are slice minimums and quota minimums in the code.  You are probably better off turning off quotas and moving to soft quotas.",
  "@d-shi: @chiluk my layman's understanding is that the default slice is 5ms, so setting it to that or less is effectly disabling it, but as long as the period is greater than 5ms there should still be quota enforcement. Definitely let me know if that's not correct.",
  "@willthames: With `--feature-gates=CustomCPUCFSQuotaPeriod=true --cpu-cfs-quota-period=10ms` one of my pods really struggled to start up. In the attached prometheus graph, the container attempts to start up, doesn't get anywhere near meeting its liveness check until it's killed (normally the container starts in about 5 seconds - even increasing the liveness initialDelaySeconds to 60s didn't help) and is then replaced by a new one.\r\n\r\nYou can see that the container is heavily throttled until I removed the cpu-cfs-quota-period from the kubelet args, at which point the throttling is a lot flatter and the cont [trimmed]",
  "@hjacobs: FYI: current Twitter thread about the topic of disabling CPU throttling: https://twitter.com/it_supertramp/status/1133648291332263936",
  "@d-shi: These are the CPU throttling graphs from before/after we moved to `--cpu-cfs-quota-period=10ms` in production for 2 latency sensitive services:\r\n\r\n<img width=\"1571\" alt=\"Screen Shot 2019-06-05 at 15 34 35\" src=\"https://user-images.githubusercontent.com/6404307/58984701-a8099800-87a7-11e9-8e4e-03c841c27e88.png\">\r\n\r\n<img width=\"1527\" alt=\"Screen Shot 2019-06-05 at 15 36 36\" src=\"https://user-images.githubusercontent.com/6404307/58984732-b952a480-87a7-11e9-95da-999ffd6dc372.png\">\r\n\r\nThese services run on different instance types (with different taints/tolerations). The 2nd service's instances wer [trimmed]",
  "@chiluk: @d-shi something else is going on on your graph.  I think there may be some minimum quota alotment that you are now hitting because the period is so small. I'd have to check to code to be sure.  Basically you inadvertently increased the amount of quota available to the application.  You probably could have accomplished the same thing by actually increasing quota allotments.",
  "@avanja: We moved to 1.8.3:\n\n```\n# docker version \nClient:\n Version:      1.8.3\n API version:  1.20\n Go version:   go1.4.2\n Git commit:   f4bf5c7\n Built:        Mon Oct 12 06:06:01 UTC 2015\n OS/Arch:      linux/amd64\n\nServer:\n Version:      1.8.3\n API version:  1.20\n Go version:   go1.4.2\n Git commit:   f4bf5c7\n Built:        Mon Oct 12 06:06:01 UTC 2015\n OS/Arch:      linux/amd64\n```\n\nbut nevertheless it continued crashing, at first once in a few days, and later up to ten times a day. Migrating from CentOS 7 with device-mapper/loopback to Ubuntu 14.04 LTS with AUFS sorted it.\n",
  "@yifan-gu: Also seen this issue https://github.com/docker/docker/issues/12606#issuecomment-149659953\n\nI can reliably reproduce the issue by running [this](https://github.com/kubernetes/kubernetes/blob/3753c9878301b0700bf9fed622fae6ebe64ea168/test/e2e/kubelet.go#L91) kubernetes's e2e tests in a loop.\n\nI caught the trace log of the daemon, seems there's a deadlock, a lot of goroutines hang on `semacquire`\n\n```\ngoroutine 8956 [semacquire, 8 minutes]:\nsync.(*Mutex).Lock(0xc208961650)\n/usr/lib/go/src/sync/mutex.go:66 +0xd3\ngithub.com/docker/docker/daemon.func028(0xc20861c1e0, 0x0, 0x0)\n/build/amd64-usr/var/tm [trimmed]",
  "@yifan-gu: Will try to test on latest version\n",
  "@yifan-gu: Tried another run, still with 1.7.1, but this time found something more interesting:\n\n```\ngoroutine 114 [syscall, 50 minutes]:\nsyscall.Syscall6(0x3d, 0x514, 0xc2084e74fc, 0x0, 0xc208499950, 0x0, 0x0, 0x44199c, 0x441e22, 0xb28140)\n/usr/lib/go/src/syscall/asm_linux_amd64.s:46 +0x5\nsyscall.wait4(0x514, 0xc2084e74fc, 0x0, 0xc208499950, 0x90, 0x0, 0x0)\n/usr/lib/go/src/syscall/zsyscall_linux_amd64.go:124 +0x79\nsyscall.Wait4(0x514, 0xc2084e7544, 0x0, 0xc208499950, 0x41a768, 0x0, 0x0)\n/usr/lib/go/src/syscall/syscall_linux.go:224 +0x60\nos.(*Process).wait(0xc2083e2b20, 0xc20848a860, 0x0, 0x0)\n/usr/lib/g [trimmed]",
  "@ohade: Thats a major issue for me, is anyone from Docker looking into this?\n",
  "@thaJeztah: ping @LK4D4 @tiborvass ^^ https://github.com/docker/docker/issues/13885#issuecomment-149767470\n",
  "@thefallentree: We have the similar issue under docker 1.8.2 , I suspect there are go routine or other leaks going in the daemon. \n\nWhen put under fast creation/deletion stress,  `docker ps` would take forever to finish, and eventually docker daemon will lost repose.\n",
  "@inter169: Each workaround or fix doesn't work for every use case, so the user, sys admin, and app developer should consider which one is fine to himself, also the costs & risks for  patching some tc/iptables scripts, updating new kernel, or patching libc musl. \r\n\r\nin my use case it was a nodejs app response timed out for 5+secs when requesting some URI's (like http://wx.qlogo.cn/**) on alpine linux docker, so I coded the fix (https://github.com/kubernetes/kubernetes/issues/56903#issuecomment-409603030) in musl libc, it's less costs & risks than patching tc scripts/iptables ruls or upgrading the hosts' k [trimmed]",
  "@Quentin-M: @dcowden The insert_failed increases where the packet is routed to land on. So if you have a single DNS server or a single master where your DNS server(s) are running, this is very easy to predict and monitor. If insert_failed does not increase, the issue is not the netfilter race condition. Note that the script may need to be adapted: I personally have my DNS server containers listen on 5353 rather than 53, so they don't need to run as root. My experience also shows that the latency may need to be increased by a few ms depending on the overlay or overall network configuration.",
  "@szuecs: @Quentin-M I ported your script (https://github.com/szuecs/flannel-tc/blob/master/tc-orig.sh) to https://github.com/szuecs/flannel-tc/blob/master/tc-flannel.sh and we run DNS on port 53 (both svc and endpoint is 53).\r\n\r\nDeployment in the flannel daemonset https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/flannel/daemonset.yaml#L92 . \r\n\r\nDNS setup:\r\nCoreDNS https://github.com/zalando-incubator/kubernetes-on-aws/tree/dev/cluster/manifests/coredns \r\ndnsmasq on local nodes cache and forward to CoreDNS https://github.com/zalando-incubator/kubernetes-on-aws/tree/dev/c [trimmed]",
  "@dcowden: @Quentin-M, @szuecs thanks for your comments!    \r\n\r\nTesting today,  we have found that our problem gets worse when we have more coredns pods running. In fact, we cannot re-create the problem when we have only one core-dns pod ( even with many clients).  \r\n\r\nI think we'll try a dnsmasq on each node. @szuecs did your approach require both tc-flannel AND node local dnsmasq to get satisfactory results, or did you do node-local dnsmasq only for performance reasons?",
  "@szuecs: @dcowden it does not fix it to 100%. flannel-tc is only to make this delay for packets at random. node-local dnsmasq will add less traffic, but we have only ~10% hit rate.\r\nI like to see what results you see with or without the node-local dnsmasq.\r\nP99 has only one or two rtt spikes per day and cluster, P999/P9999 much more often ~ >20.",
  "@brb: Just to update, I've submitted two patches to fix the conntrack races in the kernel - http://patchwork.ozlabs.org/patch/937963/ (accepted) and http://patchwork.ozlabs.org/patch/952939/ (waiting for a review).\r\n\r\nIf both are accepted, then the timeout cases due to the races will be eliminated for those who run only *one* instance of a DNS server, and for others - the timeout hit rate should decrease.\r\n\r\nTo completely eliminate when |DNS server| > 1 is a non-trivial task and is still WIP.",
  "@szuecs: @brb thanks for your work and the update here!!!\r\n\r\nCan you please explain why this >1 DNS server is a non trivial task to fix?\r\nA reference to some public e-mail thread is fine for me, if this was already discussed. It would be awesome to understand more.",
  "@blakebarnett: For us it was a lot more useful to measure latency rather than throttling. Disabling `cfs-quota` dramatically improved latency. I'd like to see similar results for changing the `cfs-quota-period`.",
  "@d-shi: @chiluk we did actually try increasing quota allotments (up to the maximum supported by kubernetes per pod), and in no case were tail end latencies nor throttling reduced by much. p99 latencies went from about 98ms at a limit of 4 cores to 86ms at a limit of 16 cores. After reducing CFS quota to 10ms p99 went to 20ms at 4 cores.\r\n\r\n@blakebarnett we developed a benchmark program that measured our latencies, and they went from a range of 10ms-100ms, with an average of around 18ms prior to updating `--cpu-cfs-quota-period`, to a range of 10ms-20ms, with an average of around 11ms afterwards. p99 l [trimmed]",
  "@chiluk: @d-shi, you were likely hitting the problem solved by 512ac999 then.",
  "@Mwea: @chiluk After reading again and again your patch, I've to admit I struggle to understand the impact of this code : \r\n```\r\n\tif (cfs_rq->expires_seq == cfs_b->expires_seq) {\r\n-\t\t/* extend local deadline, drift is bounded above by 2 ticks */\r\n-\t\tcfs_rq->runtime_expires += TICK_NSEC;\r\n-\t} else {\r\n-\t\t/* global deadline is ahead, expiration has passed */\r\n-\t\tcfs_rq->runtime_remaining = 0;\r\n-\t}\r\n```\r\n\r\nIn a case where the quota expire even if runtime_remaining just borrowed some time from the global pool. At worst you will get throttled for 5ms based on sched_cfs_bandwidth_slice_us. Isnt it?\r\nDo I mi [trimmed]",
  "@d-shi: @chiluk yes I think are right. Our production servers are still on kernel 4.4, so do not have that fix. Perhaps once we upgrade to a newer kernel we can move CFS quota period back to default, but for now it is working to improve our tail end latencies and we have not noticed any adverse side effects yet. Though it has only been live for a couple weeks.",
  "@mariusgrigoriu: @chiluk Mind summarizing the status of this issue in the kernel? Seems like there was a patch, 512ac999, but it had issues. Did I read somewhere that it got reverted? Or is this fully / partially fixed? If so, what version?",
  "@willthames: @mariusgrigoriu it's not fixed, @chiluk has created a patch that should fix it that needs further testing (I'm going to allocate some of my time in the next few days to this)\r\n\r\nSee https://github.com/kubernetes/kubernetes/issues/67577#issuecomment-482198124 for the latest status",
  "@pspierce: I'm having similar issues with 1.8.2.  I tried 1.9 rc2 and had similar issues, lots of hangs and restarting the docker daemon, which sometimes corrected things and more often didn't.\n",
  "@cpuguy83: I'd be curious to know when something hangs, how long is it hanging for before it's killed?\nDoes it ever return if you just let it wait it out?\n",
  "@pspierce: Though I didn't time it, I'd say it was at least over twenty minutes.  I've started using docker-compose kill vs. stop and it seems better, but time will tell.  I don't see anything obvious from the logs either.\n",
  "@tobowers: We see this too on centos 7.1, docker 1.8.2.  My gut tells me it's a datamapper/loopback problem.\n\nNext on our list is to try this: https://github.com/projectatomic/docker-storage-setup (h/t @ibuildthecloud )\n",
  "@chbatey: Also experiencing this and it is not under heavy load.\n\nCentos 7\n\nDocker version\n\n```\nClient:\n Version:      1.8.2\n API version:  1.20\n Go version:   go1.4.2\n Git commit:   0a8c2e3\n Built:        Thu Sep 10 19:08:45 UTC 2015\n OS/Arch:      linux/amd64\n\nServer:\n Version:      1.8.2\n API version:  1.20\n Go version:   go1.4.2\n Git commit:   0a8c2e3\n Built:        Thu Sep 10 19:08:45 UTC 2015\n OS/Arch:      linux/amd64\n\n\n```\n\nDocker info\n\n```\nContainers: 4\nImages: 40\nStorage Driver: devicemapper\n Pool Name: docker-202:1-25190844-pool\n Pool Blocksize: 65.54 kB\n Backing Filesystem: xfs\n Data file: / [trimmed]",
  "@thaJeztah: @chbatey can you edit your comment, and add the output of `docker version`?\n",
  "@pspierce: As for me and mine, color my face red.  I ran the daemon in debug and discovered a shared volume that was a cifs mount hanging.  Once I took care of that, things are working fine for me now.\n",
  "@dcowden: +1 I would like to understand more as well. It's really crazy that an issue so fundamental exists for kubernetes. \r\n\r\n@szuecs is there any configuration you are aware of that would actually eliminate this issue? Currently, the only solution I know of is to switch to tcp for dns (use-vc) but that's not supported by all distros. I also assume that using calico or vpc routing on aws would bypass it because all pods have  routable IP addresses and thus nat is never needed.  \r\n\r\nDo you think that running coredns on each node, with host Network =true would work? ",
  "@szuecs: @dcowden vpc would help, calico, I would not be sure, they have to use ipip tunnel, not sure if this deletes masquerading completely. \r\nNext step I would try is eventually https://github.com/kubernetes/kubernetes/issues/56903#issuecomment-409603030. Right now it seems my solution seems to be good enough, for us no rush is needed.",
  "@dcowden: @szuecs yes along those lines we have also considered disabling ipv6 completely on our nodes. We started to do that but weave had some interfaces listening only on ipv6 so that scared us away. \r\n\r\nHas anyone tried weave with no ipv6? ",
  "@bboreham: > weave had some interfaces listening only on ipv6\r\n\r\nDefinitely not. Pretty sure what you are looking at is a tool reporting an IPv4 address in IPv6 format. ",
  "@brb: > Can you please explain why this >1 DNS server is a non trivial task to fix?\r\n\r\nTL;DR Two different Endpoints might be selected for two concurrent UDP packets from the same socket, regardless whether kube-proxy operates in `iptables` or `ipvs` mode. If so, one of the packets will be dropped by the kernel. So far, I don't see any easy way how to sync destination selection in the kernel among such packets. Anyway, I will do a longer write-up about this.",
  "@bboreham: At this point, running kube-dns or dnsmasq on every node becomes very attractive. \r\n\r\nVarious issues discuss this - #45363 for instance. ",
  "@szuecs: @dcowden as @bboreham I would be pretty sure that it only looks like this, but is dual-stack and listens on both. \r\n\r\n@brb thanks. ",
  "@chiluk: @Mwea the global pool is stored in cfs_b->runtime_remaining.  As that gets assigned to per cpu run queues (cfs_rq), the amount remaining in the global pool gets decremented.  cfs_bandwidth_slice_us is the amount of cpu runtime that gets transferred from the global pool to the per-cpu run queues.  If you got throttled that would mean that you needed to run and cfs_b->runtime_remaining == 0.  You would have to wait for the end of the current period (by default 100ms), for quota to be replenished to cfs_b and then distributed to your cfs_rq.  I recently discovered that the amount of expired runti [trimmed]",
  "@PaulFurtado: @chiluk any chance you've already posted a version of this patch that is compatible with kernel 4.14 already? I'm looking to test it pretty aggressively since we've just upgraded a few thousand hosts to 4.14.121 (from 4.9.62) and are seeing:\r\n1. A reduction in throttling for memcached, mysql, nginx, etc\r\n2. An increase in throttling for our java apps\r\n\r\nReally want to roll forward to get the best of both worlds here. I can attempt to port it over myself next week, but if you already have one, that would be awesome.",
  "@chiluk: @PaulFurtado \r\nI have actually rewritten the patch over the last few days given Ben Segull's suggestions.  A new kernel patch will be forthcoming as soon as I can get it some test time on our clusters.",
  "@PaulFurtado: @chiluk any update on that patch? No worries if not, I'm just making sure I didn't miss the patch going by",
  "@chiluk: @PaulFurtado , the patch has been \"approved\" by the CFS author, and I'm just waiting for the scheduler maintainers to integrate it and push it to Linus.",
  "@PaulFurtado: @chiluk Thank you!\r\n\r\nI just backported the patch onto kernel 4.14, which is our current production kernel.\r\nI made a gist with the backport and some results from your fibtest here: https://gist.github.com/PaulFurtado/ff6c67ec87416b66ba1c6fc70f7beec1\r\n\r\nOn current generation c5.9xlarge and m5.24xlarge ec2 instance which we use in our kubernetes and mesos clusters, the patch doubles the performance of your fibtest program. On a previous generation r4.16xlarge instance type, it manages 1.5x more CPU utilization but barely any additional iterations (which I'm assuming is just due to the CPU gener [trimmed]",
  "@chiluk: @PaulFurtado first off thank you for the testing.  I'll assume you are running kernel.org 4.14 or the ubuntu 4.14, both of which have 512ac999 in it.  As for fibtest Iterations completed isn't as important as cpu time utilized, as iterations completed can be heavily affected by cpu mhz while running the test (especially in the cloud where I'm not sure how much control you have over that).",
  "@thaJeztah: @pspierce no problem, thank you for reporting back!\n\nI'm interested to hear if this is still an issue on 1.9 for anyone here\n",
  "@nathwill: we're also seeing this with 1.8.2 on centos 7.1 quite frequently, but only on our high-churn hosts (~2,100 containers/hour). It doesn't seem to impact our identically configured, but lower volume (~300 containers/hour) hosts, so it seems to be some kind of deadlock triggered by lots of concurrent operations? We see it ~*/6 hours of high-churn activity, and so far the only solution we've found is to run regular (~*/3 hrs) daemon restarts that nuke '/var/lib/docker/containers', and '/var/lib/docker/volumes' while the daemon's down in order to bring the host up \"fresh\" without tossing our images, [trimmed]",
  "@bavery22: Also seeing this on ubuntu 14.04, only 8 containers running but high disk and cpu load.  The containers are restarted as they complete so there are always 8 running.  The daemon is dying after anything from a few hundred to a couple of thousand cumulative container runs. I did not see the daemon hang when I was running over loopback but it's happened twice in the last couple of days using the thinpool. This is on a 40 core workstation with 64gb ram.\n\nDocker Version:\n~$ docker version\nClient:\n Version:      1.9.1\n API version:  1.21\n Go version:   go1.4.2\n Git commit:   a34a1d5\n Built:        F [trimmed]",
  "@daviesalex: We had this under 1.7.1, and worked around it very effectively (we saw it every few hours under 1.7.1, but never for 1+ month post workaround):\n\n```\nudevadm control --timeout=300\n```\n\nWe are running RHEL7.1. We just did an upgrade to Docker 1.8.2 without any other changes, and our app locked it up within a few hours. Strace:\n\n``\n[pid  4200] open(\"/sys/fs/cgroup/freezer/system.slice/docker-bcb29dad6848d250df7508f85e78ca9b83d40f0e22011869d89a176e27b7ef87.scope/freezer.state\", O_RDONLY|O_CLOEXEC) = 36\n[pid  4200] fstat(36, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0\n[pid  4239] <... select resume [trimmed]",
  "@hectorj2f: We're facing the same issue https://github.com/giantswarm/giantswarm/issues/289 \n",
  "@yfyf: UPDATE: It seems my hypothesis about interleaved `docker run` / `docker rm` was unsound. I tried to only do many simultaneous `docker run`s and that was sufficient to trigger the behavior.  I also tried to switch to a dm thinpool, but that didn't help either. My workaround was simply ensuring that multiple containers are never started at the \"same\" time, i.e. I add at least ~10-30 second gaps between the starts. Now the daemon is running without any problems for over 2 weeks.  End of update.\n\nJust to add one more confirmation, we are seeing this in 1.9.0. We are not even spawning a lot, max 8  [trimmed]",
  "@EddieJamsession: @mjsalinger We have the same problem as you, with the same setup, did you solve the problem?\n",
  "@Quentin-M: @dcowden We use Weave, with IPv6 disabled at every layers (kernel, systemd, ...).",
  "@dcowden: Thanks, guys.\r\nI \"feel\" like running dns-masq on each node is the right answer here.  The interesting question is: what IP address should the dns-masq instance expose the service on, in order to minimize packet loss ( Let's assume that we're ok ignoring security issues for the moment).\r\n\r\nThat means, we have three options:\r\n(1) daemonset on each node, but using a normal pod ip\r\n(2) daemonset on each node, but with hostNetwork true, which will expose the service on the node's ip\r\n(3) installed on the node itself, exposing the service on the weave interface for that node\r\n(4) installed on the no [trimmed]",
  "@inter169: pls be aware of that, on alpine docker such AAAA DNS queries are generated by libc musl implements, even though disabled ipv6 on the alpine docker and the hosts, so I removed the AAAA query from musl by default, see https://github.com/kubernetes/kubernetes/issues/56903#issuecomment-409603030 ,\r\nthe app pods based on my patched fix alpine (geekidea/alpine-a:3.7 , 3.8) have been working 5+days on our production kubernetes clusters (v1.9.3 + flannel + 16*kubedns pods as the kubedns svc), no AAAA queries, no timeouts for 5 secs on our nodejs apps.",
  "@dennis-bell: @inter169 Tested your solution and works perfectly, however could you point us at some documentation how to update 3.7/3.8 ourselves and build our own image with your fix?\r\n",
  "@inter169: @dennis-bell, because of the code fix in libc musl on alpine linux docker, so you should build the patched mucl libc with the code fix https://github.com/kubernetes/kubernetes/issues/56903#issuecomment-409603030 as the alpine apk manner. (https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package):\r\nalpine 3.7 is using 1.1.18-r3, see: https://pkgs.alpinelinux.org/package/v3.7/main/x86_64/musl, aport should use https://git.alpinelinux.org/cgit/aports/snapshot/aports-944a45f26d02bb803737af70cf5f012194796146.tar.bz2\r\n\r\nalpine 3.8 is using 1.1.19-r10, see https://pkgs.alpinelinux.org/package/v3. [trimmed]",
  "@dcowden: @szuecs @bboreham  I have a dnsmasq running locally, and though it is not perfect either, it does improve things considerably.   The dnsmasq is running on the local node, exposing it via the weave interface.  When a pod is configured to use this dnsmasq server, all works pretty well\r\n\r\nThat leaves the question: What methods can we use to get pods to resolve to that nameserver? So far we have lots of options, but they are all non-ideal:\r\n\r\n* **dnsPolicy=Default**  at first seems like a solution, until we realized that with this option, kubernetes no longer injects the search domains for the clu [trimmed]",
  "@szuecs: To set the DNS resolver to the right EC2 node we do this:\r\n\r\n- get the EC2 node ip: https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/node-pools/worker-default/userdata.clc.yaml#L112-L124\r\n- pass the flag with the ENV to kubelet https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/node-pools/worker-default/userdata.clc.yaml#L165\r\n\r\nLike this every POD has a /etc/resolv.conf different from every node and the first nameserver is the local one. The nameserver target is this dnsmasq daemonset https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/c [trimmed]",
  "@PaulFurtado: > I'll assume you are running kernel.org 4.14 or the ubuntu 4.14, both of which have 512ac999 in it.\r\n\r\nYes, we run mainline 4.14 (well, plus the patch set from the Amazon Linux 2 kernel, but none of those patches matter in this case).\r\n\r\n512ac999 landed in mainline 4.14.95, and we observed its affects upon upgrading from 4.14.77 to 4.14.121+. It made our memcached containers (very low thread count) go from inexplicable throttling to no throttling, but made our golang and java containers (very high thread count) experience more throttling.\r\n\r\n> As for fibtest Iterations completed isn't as impo [trimmed]",
  "@jhohertz: Just wanted to leave a note, regarding the kernel patch being discussed....\r\n\r\n I have adapted it to the kernel we're using in current testing, and see some huge wins on CFS throttling rates, however I will mention that if you have previously set the cfs period down to 10ms as a mitigation, you're going to want to bring that back up to 100ms to see the benefits of the change.\r\n",
  "@chiluk: The patch landed on tip this morning. \r\nhttps://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=de53fd7aedb100f03e5d2231cfce0e4993282425\r\n\r\nOnce it hits Torvald's tree, I'll submit it for linux-stable inclusion, and subsequently major distros (Redhat/Ubuntu).  If you care about something else, and they aren't following linux-stable patches you might want to submit it directly.",
  "@zigmund: I've tested patch (ubuntu 18.04, 5.2.7 kernel, node: 56 core CPU E5-2660 v4 @ 2.00GHz) with our cpu-heavy image processing golang microservice and got pretty impressive results. Performance like if I disable CFS on node completelly.\r\n\r\nI've got 5-35% less latency and 5-55% more RPS depending on concurrency / CPU utilization at near zero throttling rate.\r\n\r\nThanks, @chiluk !\r\n\r\nAs said @jhohertz , cfs quota should be reverted to 100ms, I've tested with lower periods and got high throttling and performance degradation.",
  "@chiluk: For more performance with golang set GOMAXPROCS to ceil(quota)+2.  The plus 2 is to guarantee some concurrency.",
  "@zigmund: @chiluk tested with GOMAXPROCS=8 vs GOMAXPROCS=10 with cpu.limit=8 - not a big difference, something about 1-2%.",
  "@chiluk: @zigmund that's because your cpu.limit is set to the whole number 8 which should bind your processes to a cpuset of 8 cpus.  Your 1-2% difference is just the increase in overhead for context switching with your 2 additional Goroutine runners on your 8 cpu taskset.\r\n\r\nI should have said that setting GOMAXPROCS=# is a good workaround for go programs until the kernel patches get widely distributed.",
  "@chr0n1x: Same issue here\n\n```\n~ # docker info\nContainers: 118\nImages: 2239\nStorage Driver: overlay\n Backing Filesystem: extfs\nExecution Driver: native-0.2\nLogging Driver: json-file\nKernel Version: 4.2.2-coreos-r1\nOperating System: CoreOS 835.8.0\nCPUs: 16\nTotal Memory: 29.44 GiB\nUsername: util-user\nRegistry: https://index.docker.io/v1/\nClient:\n Version:      1.8.3\n API version:  1.20\n Go version:   go1.4.2\n Git commit:   cedd534-dirty\n Built:        Tue Dec  1 02:00:58 UTC 2015\n OS/Arch:      linux/amd64\n\nServer:\n Version:      1.8.3\n API version:  1.20\n Go version:   go1.4.2\n Git commit:   cedd534-dirt [trimmed]",
  "@whosthatknocking: Including dump of all docker goroutines stacks by sending SIGUSR1 to a daemon might be helpful ..\n",
  "@chr0n1x: @whosthatknocking didn't even know I could do that, cool.\n\n```\ntime=\"2016-01-08T22:20:16.181468178Z\" level=info msg=\"=== BEGIN goroutine stack dump ===\ngoroutine 11 [running]:\ngithub.com/docker/docker/pkg/signal.DumpStacks()\n    /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.8.3/work/docker-1.8.3/.gopath/src/github.com/docker/docker/pkg/signal/trap.go:60 +0x7a\ngithub.com/docker/docker/daemon.func025()\n    /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.8.3/work/docker-1.8.3/.gopath/src/github.com/docker/docker/daemon/debugtrap_unix.go:18 +0x6d\ncreated by github.com/docker/dock [trimmed]",
  "@rwky: I just had the hang, docker go routines attached [docker-hang.txt](https://github.com/docker/docker/files/86455/docker-hang.txt)\n",
  "@rwky: I'm also seeing this repeatedly in the logs after a hang\n`kernel: unregister_netdevice: waiting for veth2fb10a9 to become free. Usage count = 1`\n",
  "@thaJeztah: @rwky possibly related to https://github.com/docker/docker/issues/5618?\n",
  "@rwky: @thaJeztah possibly however #5618 seems to only apply to lo and eth0 not the interface that the container was bound to.\n",
  "@bboreham: @dcowden as I said, other issues (e.g. #45363) discuss the question of how to access the DNS on every node, so I don't want to get into the discussion in this one.",
  "@dcowden: @szuecs brilliant! thanks for that suggestion of using --cluster-dns.  im not sure if that will work for us, since we use kops, but we can try it!\r\n\r\n",
  "@dcowden: For what its worth for future readers, we have hammered out a solution that seems to work really well.  \r\n\r\n**Solution Overview**\r\nRuns dnsmasq on each node.\r\nexpose to the pods via a static ip on a new local adapter on an ip that is the same for all nodes. \r\nkubelets --cluster-dns points to this ip address\r\n\r\n \r\n**How the solution performs**\r\nTest Cluster details:\r\n* kubernetes 1.10.3\r\n* built by kops  1.10.beta-2 on aws\r\n* nodes are centos\r\n* 3-az cluster, 3 masters 6 workers\r\n* coredns, 4 pods ( up from the standard 2: more makes the problem worse)\r\n\r\nWe used [this dns-tester ](https://gith [trimmed]",
  "@zigmund: We've migrated our production clusters to patched kernel and now I can share you some interesting moments.\r\nStatistics from one of our clusters - 4 nodes of 72 core E5-2695 v4 @ 2.10GHz, 128Gb RAM, Debian 9, 5.2.7 kernel with patch.\r\nWe have mixed loads consist mostly of golang services, but also have php and python.\r\n\r\nGolang. Latency is lower, setting correct GOMAXPROCS is absolutely must-have. Here is service with default GOMAXPROCS=72. We've changed the kernel at ~16 and after that latency gone down and CPU utilization gone up heavily. At 21:15 I set correct GOMAXPROCS and CPU utilization  [trimmed]",
  "@prune998: Thanks @zigmund.\r\nI'm not sure I get it when you say ` I setted correct GOMAXPROCS`... \r\nI assume you're not running only one pod on the 72 cores node, so you set `GOMAXPROCS` to something lower, maybe equal to the Pod's CPU Limits right ? \r\n",
  "@chiluk: Thanks @zigmund.  The go changes are pretty much in line with what was expected.\r\n\r\nI'm really surprised by the python improvements though as I expected the GIL to largely negate the benefits of this.  If anything this patch should almost purely decrease response time, decrease percentage of periods throttled, and increase cpu utilization.  Are you sure your python application was still healthy?",
  "@stainboy: Same issue happened when heavy load of Kubernetes jobs were scheduled. `docker ps` never returns. Actually `curl --unix-socket /var/run/docker.sock http:/containers/json` hangs. I have to restart docker daemon to recover the issue. What's worse is it takes couple minutes to restart docker daemon!\n\n```\n$ docker version\nClient:\n Version:      1.8.3\n API version:  1.20\n Go version:   go1.4.3\n Git commit:   cedd534-dirty\n Built:        Thu Nov 19 23:12:57 UTC 2015\n OS/Arch:      linux/amd64\n\nServer:\n Version:      1.8.3\n API version:  1.20\n Go version:   go1.4.3\n Git commit:   cedd534-dirty\n Built [trimmed]",
  "@Rucknar: Seeing something similar on my our environment, dumped the info out below to aid any debugging. Stats are from two high spec physical rancheros4.2 hosts running around 70 containers each. We see the performance of docker degrade, i've not managed to track down the trigger, but a restart of the docker daemon does resolve the issue. \n\nDocker version\n\n```\nClient:\n Version:      1.9.1\n API version:  1.21\n Go version:   go1.4.3\n Git commit:   994543b\n Built:        Mon Nov 23 06:08:57 UTC 2015\n OS/Arch:      linux/amd64\n\nServer:\n Version:      1.9.1\n API version:  1.21\n Go version:   go1.4.3\n Git c [trimmed]",
  "@ssalinas: +1 to this for us as well, definitely seeing it more often under higher load, running on centos 6\n\nDocker Version\n\n```\nClient version: 1.7.1\nClient API version: 1.19\nGo version (client): go1.4.2\nGit commit (client): 786b29d\nOS/Arch (client): linux/amd64\nServer version: 1.7.1\nServer API version: 1.19\nGo version (server): go1.4.2\nGit commit (server): 786b29d\nOS/Arch (server): linux/amd64\n```\n\nDocker Info\n\n```\nContainers: 1\nImages: 55\nStorage Driver: overlay\n Backing Filesystem: extfs\nExecution Driver: native-0.2\nLogging Driver: json-file\nKernel Version: 3.18.23-74.el6.x86_64\nOperating System: <u [trimmed]"
]

TIMESTAMPS = [
  "2017-12-08T04:11:32Z",
  "2017-12-10T07:19:22Z",
  "2017-12-23T14:45:56Z",
  "2018-01-06T00:29:18Z",
  "2018-01-09T20:42:03Z",
  "2018-01-19T17:30:29Z",
  "2018-01-19T20:01:33Z",
  "2018-08-20T13:15:24Z",
  "2018-08-20T14:44:28Z",
  "2018-08-21T23:04:15Z",
  "2018-08-22T07:18:54Z",
  "2018-08-23T00:30:19Z",
  "2018-08-30T13:35:44Z",
  "2018-08-30T18:33:53Z",
  "2015-06-11T13:26:17Z",
  "2015-06-11T13:43:54Z",
  "2015-06-11T15:11:28Z",
  "2015-06-11T15:14:59Z",
  "2015-06-12T00:17:50Z",
  "2015-06-13T11:17:50Z",
  "2015-06-14T18:53:43Z",
  "2018-01-19T20:23:50Z",
  "2018-01-19T20:31:17Z",
  "2018-01-19T20:50:07Z",
  "2018-01-19T20:52:30Z",
  "2018-01-19T20:56:00Z",
  "2018-01-22T16:28:45Z",
  "2018-01-23T19:09:47Z",
  "2018-11-26T14:34:33Z",
  "2018-11-27T08:30:26Z",
  "2018-11-27T12:34:58Z",
  "2018-11-27T12:59:24Z",
  "2018-11-27T23:43:10Z",
  "2019-02-11T23:18:24Z",
  "2019-02-12T09:20:38Z",
  "2015-06-16T01:06:06Z",
  "2015-06-16T03:22:23Z",
  "2015-06-16T05:52:25Z",
  "2015-06-16T14:03:09Z",
  "2015-06-16T14:14:05Z",
  "2015-06-16T17:33:57Z",
  "2015-06-16T19:17:27Z",
  "2018-01-24T00:03:23Z",
  "2018-01-26T20:51:40Z",
  "2018-02-05T14:56:35Z",
  "2018-04-03T17:38:23Z",
  "2018-04-12T12:11:36Z",
  "2018-04-14T15:35:44Z",
  "2018-04-17T21:20:32Z",
  "2019-02-14T21:17:52Z",
  "2019-02-15T04:44:14Z",
  "2019-02-23T02:45:27Z",
  "2019-03-25T13:38:29Z",
  "2019-03-25T14:36:06Z",
  "2019-03-25T14:45:57Z",
  "2019-03-25T15:54:37Z",
  "2015-06-16T19:20:09Z",
  "2015-06-16T19:57:09Z",
  "2015-06-17T00:07:42Z",
  "2015-06-17T05:23:27Z",
  "2015-06-17T17:28:53Z",
  "2015-06-17T19:10:45Z",
  "2015-06-19T01:25:44Z",
  "2018-04-18T04:47:15Z",
  "2018-04-18T05:14:13Z",
  "2018-04-18T05:17:18Z",
  "2018-04-18T14:33:33Z",
  "2018-04-18T15:51:12Z",
  "2018-04-18T16:01:28Z",
  "2018-04-30T22:34:04Z",
  "2019-03-25T18:41:12Z",
  "2019-03-25T18:58:54Z",
  "2019-03-27T06:03:01Z",
  "2019-03-27T12:44:53Z",
  "2019-03-27T13:36:11Z",
  "2019-03-27T13:50:13Z",
  "2019-03-27T14:53:28Z",
  "2015-06-19T01:41:07Z",
  "2015-06-19T08:50:14Z",
  "2015-06-19T16:00:54Z",
  "2015-06-23T12:00:57Z",
  "2015-06-23T19:22:16Z",
  "2015-06-25T10:45:38Z",
  "2015-06-25T21:21:00Z",
  "2018-05-02T00:33:15Z",
  "2018-05-15T23:04:42Z",
  "2018-05-21T21:22:15Z",
  "2018-05-24T10:09:34Z",
  "2018-05-24T19:17:47Z",
  "2018-05-31T12:40:17Z",
  "2018-05-31T16:31:02Z",
  "2019-04-02T11:29:45Z",
  "2019-04-02T11:47:43Z",
  "2019-04-03T23:23:41Z",
  "2019-04-05T13:08:26Z",
  "2019-04-05T14:29:40Z",
  "2019-04-05T17:06:45Z",
  "2019-04-05T19:19:10Z",
  "2015-06-26T10:06:22Z",
  "2015-07-01T11:04:21Z",
  "2015-07-01T17:39:11Z",
  "2015-07-01T19:14:38Z",
  "2015-07-10T00:37:05Z",
  "2015-08-05T14:25:44Z",
  "2015-08-12T16:01:08Z",
  "2018-06-01T09:39:10Z",
  "2018-06-01T16:47:51Z",
  "2018-06-04T16:58:31Z",
  "2018-06-14T19:02:26Z",
  "2018-06-24T23:06:44Z",
  "2018-06-25T09:44:12Z",
  "2018-06-25T17:33:03Z",
  "2019-04-11T16:52:41Z",
  "2019-05-21T18:25:14Z",
  "2019-05-28T22:32:21Z",
  "2019-05-29T05:34:10Z",
  "2019-05-29T07:36:02Z",
  "2019-05-29T11:16:35Z",
  "2019-05-29T14:16:04Z",
  "2015-08-21T07:33:26Z",
  "2015-09-19T01:51:03Z",
  "2015-09-20T07:56:37Z",
  "2015-09-20T10:18:02Z",
  "2015-09-29T16:33:58Z",
  "2015-09-30T21:22:21Z",
  "2015-10-01T05:18:42Z",
  "2018-06-27T11:38:35Z",
  "2018-06-27T11:47:25Z",
  "2018-06-27T12:02:48Z",
  "2018-06-27T12:26:05Z",
  "2018-06-27T12:33:15Z",
  "2018-07-12T16:08:12Z",
  "2018-07-16T16:50:49Z",
  "2019-05-29T14:21:19Z",
  "2019-05-29T14:22:59Z",
  "2019-05-29T17:20:57Z",
  "2019-05-29T17:25:01Z",
  "2019-05-29T17:39:38Z",
  "2019-05-29T17:56:45Z",
  "2019-05-29T18:11:35Z",
  "2015-10-01T10:33:59Z",
  "2015-10-01T11:01:54Z",
  "2015-10-02T09:43:32Z",
  "2015-10-02T09:55:22Z",
  "2015-10-13T14:40:16Z",
  "2015-10-20T01:55:18Z",
  "2015-10-20T01:58:38Z",
  "2018-07-20T16:14:18Z",
  "2018-08-01T14:52:19Z",
  "2018-08-03T04:22:02Z",
  "2018-08-03T04:59:10Z",
  "2018-08-03T09:32:36Z",
  "2018-08-03T16:29:17Z",
  "2018-08-03T17:08:02Z",
  "2019-05-29T22:00:58Z",
  "2019-05-30T21:16:15Z",
  "2019-05-30T22:27:08Z",
  "2019-06-05T00:29:50Z",
  "2019-06-05T07:38:11Z",
  "2019-06-05T19:37:14Z",
  "2019-06-05T21:56:03Z",
  "2015-10-20T07:09:08Z",
  "2015-10-20T22:24:35Z",
  "2015-10-20T22:31:28Z",
  "2015-10-21T02:54:20Z",
  "2015-10-21T07:59:44Z",
  "2015-10-21T08:04:29Z",
  "2015-10-26T06:42:05Z",
  "2018-08-03T18:11:34Z",
  "2018-08-03T19:02:29Z",
  "2018-08-03T19:27:40Z",
  "2018-08-03T22:34:49Z",
  "2018-08-05T11:25:19Z",
  "2018-08-05T11:56:02Z",
  "2018-08-05T12:03:08Z",
  "2019-06-05T22:42:29Z",
  "2019-06-06T19:55:05Z",
  "2019-06-06T20:20:20Z",
  "2019-06-06T20:47:37Z",
  "2019-06-06T21:50:48Z",
  "2019-06-07T00:06:38Z",
  "2019-06-07T00:15:04Z",
  "2015-11-02T20:16:10Z",
  "2015-11-02T20:23:54Z",
  "2015-11-02T20:52:30Z",
  "2015-11-03T00:49:58Z",
  "2015-11-05T10:10:59Z",
  "2015-11-05T10:15:10Z",
  "2015-11-05T16:47:32Z",
  "2018-08-05T13:08:26Z",
  "2018-08-05T13:50:33Z",
  "2018-08-05T13:57:41Z",
  "2018-08-05T14:59:14Z",
  "2018-08-05T15:09:15Z",
  "2018-08-05T15:32:04Z",
  "2018-08-05T17:31:14Z",
  "2019-06-07T16:29:50Z",
  "2019-06-21T08:13:03Z",
  "2019-06-24T15:14:38Z",
  "2019-07-18T21:37:44Z",
  "2019-07-24T18:58:22Z",
  "2019-07-26T06:17:41Z",
  "2019-07-31T01:52:49Z",
  "2015-11-05T16:50:41Z",
  "2015-11-20T17:20:32Z",
  "2015-12-03T21:17:55Z",
  "2015-12-08T19:14:06Z",
  "2015-12-15T18:35:03Z",
  "2015-12-23T14:13:37Z",
  "2016-01-07T13:30:41Z",
  "2018-08-05T19:09:02Z",
  "2018-08-05T23:48:04Z",
  "2018-08-06T01:31:49Z",
  "2018-08-06T07:22:42Z",
  "2018-08-06T08:10:53Z",
  "2018-08-07T16:00:43Z",
  "2018-08-07T16:12:29Z",
  "2019-07-31T03:57:32Z",
  "2019-08-06T17:56:06Z",
  "2019-08-08T13:54:12Z",
  "2019-08-10T17:57:25Z",
  "2019-08-12T21:29:57Z",
  "2019-08-13T04:32:30Z",
  "2019-08-26T14:45:43Z",
  "2016-01-08T21:46:31Z",
  "2016-01-08T21:58:53Z",
  "2016-01-08T22:24:51Z",
  "2016-01-11T21:56:37Z",
  "2016-01-11T22:26:39Z",
  "2016-01-12T19:42:12Z",
  "2016-01-12T22:04:08Z",
  "2018-08-07T17:06:58Z",
  "2018-08-07T18:10:22Z",
  "2018-08-08T13:22:01Z",
  "2019-09-03T17:35:38Z",
  "2019-09-03T17:51:47Z",
  "2019-09-03T19:08:29Z",
  "2016-01-14T13:24:43Z",
  "2016-01-17T22:26:01Z",
  "2016-01-23T02:13:03Z"
]

TOPICS = [
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "DNS delays",
  "DNS delays",
  "DNS delays",
  "CFS throttling",
  "CFS throttling",
  "CFS throttling",
  "Docker daemon hangs",
  "Docker daemon hangs",
  "Docker daemon hangs"
]

FACTS = [
  {
    "topic": "DNS delays",
    "msg_index": 1,
    "question": "What DNS server IP does kgignatyev-inspur report?",
    "answer": "100.64.0.10"
  },
  {
    "topic": "DNS delays",
    "msg_index": 2,
    "question": "What GKE version does ani82 observe the DNS issue on?",
    "answer": "v1.8.4-gke0"
  },
  {
    "topic": "DNS delays",
    "msg_index": 27,
    "question": "What resolv.conf option did vasartori find fixes the DNS problem?",
    "answer": "single-request-reopen"
  },
  {
    "topic": "DNS delays",
    "msg_index": 42,
    "question": "What GKE version does aca02djr report the issue on?",
    "answer": "1.8.6-gke.0"
  },
  {
    "topic": "DNS delays",
    "msg_index": 5,
    "question": "What was the cause of DNS delays in aguerra's case?",
    "answer": "arp table overflow"
  },
  {
    "topic": "CFS throttling",
    "msg_index": 10,
    "question": "What kubelet flag does hjacobs mention to disable CFS quota?",
    "answer": "--cpu-cfs-quota=false"
  },
  {
    "topic": "CFS throttling",
    "msg_index": 13,
    "question": "According to vishh, what is the best approach for clusters running trusted workloads?",
    "answer": "turning off CPU quota"
  },
  {
    "topic": "CFS throttling",
    "msg_index": 34,
    "question": "Who contributed a flag to Kops to disable CPU throttling?",
    "answer": "hrzbrg"
  },
  {
    "topic": "CFS throttling",
    "msg_index": 31,
    "question": "According to timoreimann, has Google exposed the knobs to disable CFS on GKE?",
    "answer": "no"
  },
  {
    "topic": "CFS throttling",
    "msg_index": 9,
    "question": "According to bobrik, is the CFS issue a configuration tradeoff or a kernel bug?",
    "answer": "kernel bug"
  },
  {
    "topic": "Docker daemon hangs",
    "msg_index": 15,
    "question": "What Docker image is mjsalinger using?",
    "answer": "kinvey/blrunner"
  },
  {
    "topic": "Docker daemon hangs",
    "msg_index": 18,
    "question": "What does lsof | wc -l show when Docker becomes unresponsive?",
    "answer": "1025"
  },
  {
    "topic": "Docker daemon hangs",
    "msg_index": 19,
    "question": "What OS is mjsalinger using according to unclejack?",
    "answer": "Ubuntu 14.04"
  },
  {
    "topic": "Docker daemon hangs",
    "msg_index": 40,
    "question": "What kernel version does unclejack recommend for Ubuntu 14.04?",
    "answer": "3.13"
  },
  {
    "topic": "Docker daemon hangs",
    "msg_index": 38,
    "question": "What storage driver does mjsalinger say caused I/O bottlenecks?",
    "answer": "AUFS"
  }
]
